import React, { useState, useMemo } from 'react';
import { useAuth } from '../auth/AuthContext';
import {
  MILL_DECISION_PRESETS,
  evaluateDecision,
  analyzeCustomDilemma,
  type DecisionScenario,
  type PriorityWeights,
} from './decisionEngine';
import {
  Sparkles,
  Bot,
  Sliders,
  CheckCircle2,
  AlertTriangle,
  Flame,
  Factory,
  Droplet,
  Truck,
  RotateCw,
  Wrench,
  Search,
  Copy,
  Check,
  Printer,
  ChevronRight,
  TrendingUp,
  ShieldCheck,
  Scale,
  Zap,
  Info,
  HelpCircle,
} from 'lucide-react';

export const AiDecisionAgentView: React.FC = () => {
  const { user } = useAuth();

  const [selectedScenarioId, setSelectedScenarioId] = useState<string>('pulp-blend-gsm18');
  const [customQuery, setCustomQuery] = useState('');
  const [customScenario, setCustomScenario] = useState<DecisionScenario | null>(null);
  const [copiedSummary, setCopiedSummary] = useState(false);

  // Active scenario object
  const activeScenario = useMemo<DecisionScenario>(() => {
    if (customScenario && selectedScenarioId === customScenario.id) {
      return customScenario;
    }
    const found = MILL_DECISION_PRESETS.find(p => p.id === selectedScenarioId);
    return found || MILL_DECISION_PRESETS[0];
  }, [selectedScenarioId, customScenario]);

  // Priority Weights State (Initialized with scenario defaults)
  const [weights, setWeights] = useState<PriorityWeights>(() => activeScenario.defaultWeights);

  // When switching preset scenarios, sync weights
  const handleSelectScenario = (scenario: DecisionScenario) => {
    setSelectedScenarioId(scenario.id);
    setWeights(scenario.defaultWeights);
  };

  // Custom Query Handler
  const handleCustomAnalyze = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customQuery.trim()) return;

    const generated = analyzeCustomDilemma(customQuery.trim(), weights);
    setCustomScenario(generated);
    setSelectedScenarioId(generated.id);
    setWeights(generated.defaultWeights);
  };

  // Evaluate Decision with real-time weights
  const evaluation = useMemo(() => {
    return evaluateDecision(activeScenario, weights);
  }, [activeScenario, weights]);

  const { winningOption, confidenceScore, verdictRationale, actionSteps, scoredOptions, criticalUncertainties } = evaluation;

  // Copy Executive Summary for WhatsApp / Management
  const handleCopySummary = () => {
    const text = `📋 *SAHEB PAPER MILL - AI DECISION BRIEFING*
*Dilemma:* ${activeScenario.title}
*Winner:* ${winningOption.name} (Confidence: ${confidenceScore}%)
*Rationale:* ${verdictRationale}

*Key Action Steps:*
${actionSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

*Critical Uncertainties to Verify:*
${criticalUncertainties.map(u => `• ${u.variable}: ${u.actionToVerify}`).join('\n')}

_Generated by Saheb AI Decision Agent_`;

    navigator.clipboard.writeText(text);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2500);
  };

  // Helper icons for categories
  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'Raw Material':
        return <Factory className="h-4 w-4 text-emerald-500" />;
      case 'Boiler & Energy':
        return <Flame className="h-4 w-4 text-orange-500" />;
      case 'ETP & Chemicals':
        return <Droplet className="h-4 w-4 text-blue-500" />;
      case 'Logistics & Dispatch':
        return <Truck className="h-4 w-4 text-indigo-500" />;
      case 'Production & Rewinder':
        return <RotateCw className="h-4 w-4 text-purple-500" />;
      case 'Spare Parts & Maintenance':
        return <Wrench className="h-4 w-4 text-amber-500" />;
      default:
        return <Bot className="h-4 w-4 text-primary" />;
    }
  };

  return (
    <div className="space-y-6 font-sans max-w-7xl mx-auto pb-12">
      
      {/* 1. Top Hero Header Banner */}
      <div className="bg-gradient-to-r from-blue-700 via-indigo-700 to-slate-900 rounded-3xl p-6 sm:p-8 text-white shadow-xl relative overflow-hidden">
        <div className="absolute right-0 top-0 translate-x-8 -translate-y-8 w-64 h-64 bg-white/5 rounded-full blur-3xl pointer-events-none" />
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
          <div className="space-y-2">
            <div className="flex items-center gap-2.5">
              <div className="p-2.5 rounded-2xl bg-white/15 backdrop-blur-md border border-white/20 text-white shadow-inner">
                <Sparkles className="h-6 w-6 text-amber-300 animate-pulse" />
              </div>
              <h2 className="text-xl sm:text-2xl font-black tracking-tight font-heading">
                Paper Mill AI Decision Agent & Strategy Advisor
              </h2>
            </div>
            <p className="text-xs sm:text-sm text-blue-100/90 font-medium max-w-2xl leading-relaxed">
              Filters marketing noise, evaluates paper mill trade-offs across 5 core operational pillars, and delivers <strong>one clear, actionable recommendation</strong>.
            </p>
          </div>

          <div className="flex items-center gap-2.5 shrink-0">
            <button
              onClick={handleCopySummary}
              className="px-4 py-2.5 rounded-xl bg-white/10 hover:bg-white/20 border border-white/20 text-white font-black text-xs transition cursor-pointer flex items-center gap-2 shadow-sm"
              title="Copy Executive Summary"
            >
              {copiedSummary ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}
              <span>{copiedSummary ? 'Copied to Clipboard!' : 'Copy Summary'}</span>
            </button>
            <button
              onClick={() => window.print()}
              className="px-4 py-2.5 rounded-xl bg-white/10 hover:bg-white/20 border border-white/20 text-white font-black text-xs transition cursor-pointer flex items-center gap-2 shadow-sm"
              title="Print Decision Matrix"
            >
              <Printer className="h-4 w-4" />
              <span>Print</span>
            </button>
          </div>
        </div>
      </div>

      {/* 2. Dilemma Selector & Custom Dilemma Input */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 sm:p-6 shadow-xs space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Scale className="h-4 w-4 text-primary dark:text-blue-400" />
            <h3 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider">
              Select Factory Decision Dilemma
            </h3>
          </div>
          <span className="text-[11px] font-bold text-slate-400">
            {MILL_DECISION_PRESETS.length} Factory Scenarios Available
          </span>
        </div>

        {/* Preset Chips */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5">
          {MILL_DECISION_PRESETS.map((preset) => {
            const isSelected = activeScenario.id === preset.id;
            return (
              <button
                key={preset.id}
                type="button"
                onClick={() => handleSelectScenario(preset)}
                className={`p-3 rounded-2xl border text-left transition cursor-pointer flex items-start gap-3 ${
                  isSelected
                    ? 'bg-blue-50/80 dark:bg-blue-950/40 border-primary text-slate-900 dark:text-white shadow-xs ring-2 ring-primary/20'
                    : 'bg-slate-50/60 dark:bg-slate-800/40 border-slate-200/80 dark:border-slate-700/80 text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800'
                }`}
              >
                <div className="p-2 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-700 shrink-0 mt-0.5">
                  {getCategoryIcon(preset.category)}
                </div>
                <div className="min-w-0 flex-1">
                  <span className="text-[9px] font-black uppercase text-slate-400 dark:text-slate-500 block">
                    {preset.category}
                  </span>
                  <span className="text-xs font-black line-clamp-1 text-slate-900 dark:text-white">
                    {preset.title}
                  </span>
                  <p className="text-[10px] text-slate-500 dark:text-slate-400 line-clamp-1 mt-0.5 font-medium">
                    {preset.question}
                  </p>
                </div>
              </button>
            );
          })}
        </div>

        {/* Custom Query Input Bar */}
        <form onSubmit={handleCustomAnalyze} className="pt-2 border-t border-slate-100 dark:border-slate-800 flex gap-2">
          <div className="relative flex-1">
            <Search className="h-4 w-4 text-slate-400 absolute left-3.5 top-3" />
            <input
              type="text"
              value={customQuery}
              onChange={e => setCustomQuery(e.target.value)}
              placeholder="Or ask any custom dilemma (e.g. Which vendor to choose for starch dosing?)..."
              className="w-full pl-10 pr-4 py-2.5 bg-slate-50 dark:bg-slate-800/70 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-primary text-slate-900 dark:text-white placeholder-slate-400"
            />
          </div>
          <button
            type="submit"
            className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-black text-xs uppercase tracking-wider rounded-xl shadow-md transition cursor-pointer flex items-center gap-1.5 shrink-0"
          >
            <Bot className="h-4 w-4" />
            <span>Analyze Custom</span>
          </button>
        </form>
      </div>

      {/* 3. ACTIVE DILEMMA QUESTION & CONTEXT CARD */}
      <div className="bg-slate-50 dark:bg-slate-800/40 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 sm:p-6 space-y-2">
        <div className="flex items-center gap-2">
          <span className="px-2.5 py-0.5 rounded-full bg-blue-100 dark:bg-blue-950/60 text-primary dark:text-blue-300 text-[10px] font-black uppercase tracking-wider border border-blue-200 dark:border-blue-800">
            Active Question
          </span>
          <h3 className="text-base sm:text-lg font-black text-slate-900 dark:text-white font-heading">
            {activeScenario.question}
          </h3>
        </div>
        <p className="text-xs text-slate-600 dark:text-slate-400 font-medium leading-relaxed pl-1">
          <strong>Context:</strong> {activeScenario.backgroundContext}
        </p>
      </div>

      {/* 4. THE VERDICT (ONE CLEAR WINNING RECOMMENDATION) - THE HERO CARD */}
      <div className="bg-gradient-to-br from-emerald-500/10 via-teal-500/10 to-blue-500/10 dark:from-emerald-950/40 dark:via-teal-950/30 dark:to-slate-900 border-2 border-emerald-400/80 dark:border-emerald-700/80 rounded-3xl p-6 sm:p-8 shadow-lg relative overflow-hidden space-y-5">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-emerald-200/80 dark:border-emerald-800/80 pb-4">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white flex items-center justify-center shadow-lg shadow-emerald-500/30 shrink-0">
              <CheckCircle2 className="h-7 w-7" />
            </div>
            <div>
              <span className="text-[10px] font-black uppercase tracking-widest text-emerald-700 dark:text-emerald-400 block">
                ★ AI RECOMMENDATION VERDICT
              </span>
              <h2 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white tracking-tight">
                {winningOption.name}
              </h2>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <div className="text-right">
              <span className="text-[10px] font-extrabold text-slate-500 dark:text-slate-400 uppercase block">Confidence Level</span>
              <span className="text-base font-black font-mono text-emerald-600 dark:text-emerald-400">
                {confidenceScore}% High Confidence
              </span>
            </div>
            <div className="w-12 h-12 rounded-full border-4 border-emerald-500 flex items-center justify-center font-mono font-black text-xs bg-white dark:bg-slate-900 text-emerald-600 dark:text-emerald-400 shadow-sm">
              {scoredOptions[0].compositeScore}
            </div>
          </div>
        </div>

        {/* 2-Sentence Clear Rationale */}
        <div className="space-y-1 bg-white/80 dark:bg-slate-900/80 p-4 rounded-2xl border border-emerald-200/60 dark:border-emerald-900/60">
          <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block">
            Why This Wins (Noise-Free Rationale)
          </span>
          <p className="text-xs sm:text-sm font-bold text-slate-800 dark:text-slate-200 leading-relaxed">
            {verdictRationale}
          </p>
        </div>

        {/* Action Steps Blueprint */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
          {actionSteps.map((step, idx) => (
            <div
              key={idx}
              className="p-3.5 bg-white/90 dark:bg-slate-900/90 rounded-2xl border border-slate-200/80 dark:border-slate-700/80 space-y-1.5"
            >
              <div className="flex items-center gap-1.5 text-emerald-600 dark:text-emerald-400 text-xs font-black">
                <span className="w-5 h-5 rounded-full bg-emerald-100 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 flex items-center justify-center text-[10px]">
                  {idx + 1}
                </span>
                <span>Action Step {idx + 1}</span>
              </div>
              <p className="text-xs font-semibold text-slate-700 dark:text-slate-300">
                {step}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* 5. INTERACTIVE PRIORITY WEIGHT SLIDERS (Real-time recalculation) */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 sm:p-6 shadow-xs space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Sliders className="h-4 w-4 text-primary dark:text-blue-400" />
            <h3 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider">
              Adjust Factory Priority Weights (Live Recalculation)
            </h3>
          </div>
          <button
            type="button"
            onClick={() => setWeights(activeScenario.defaultWeights)}
            className="text-xs font-extrabold text-primary dark:text-blue-400 hover:underline cursor-pointer"
          >
            Reset Defaults
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
          {/* Cost Slider */}
          <div className="space-y-1.5 p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/80 dark:border-slate-700/80">
            <div className="flex justify-between text-xs font-bold">
              <span className="text-slate-700 dark:text-slate-300">Cost Savings</span>
              <span className="font-mono text-primary font-black">{weights.cost}%</span>
            </div>
            <input
              type="range"
              min="0"
              max="100"
              value={weights.cost}
              onChange={e => setWeights({ ...weights, cost: Number(e.target.value) })}
              className="w-full accent-blue-600 cursor-pointer"
            />
            <span className="text-[10px] text-slate-400 font-medium block">Lowest expense / ton</span>
          </div>

          {/* Quality Slider */}
          <div className="space-y-1.5 p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/80 dark:border-slate-700/80">
            <div className="flex justify-between text-xs font-bold">
              <span className="text-slate-700 dark:text-slate-300">Quality & Finish</span>
              <span className="font-mono text-purple-600 font-black">{weights.quality}%</span>
            </div>
            <input
              type="range"
              min="0"
              max="100"
              value={weights.quality}
              onChange={e => setWeights({ ...weights, quality: Number(e.target.value) })}
              className="w-full accent-purple-600 cursor-pointer"
            />
            <span className="text-[10px] text-slate-400 font-medium block">Brightness & Tensile</span>
          </div>

          {/* Speed Slider */}
          <div className="space-y-1.5 p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/80 dark:border-slate-700/80">
            <div className="flex justify-between text-xs font-bold">
              <span className="text-slate-700 dark:text-slate-300">Speed & Throughput</span>
              <span className="font-mono text-orange-600 font-black">{weights.speed}%</span>
            </div>
            <input
              type="range"
              min="0"
              max="100"
              value={weights.speed}
              onChange={e => setWeights({ ...weights, speed: Number(e.target.value) })}
              className="w-full accent-orange-600 cursor-pointer"
            />
            <span className="text-[10px] text-slate-400 font-medium block">Clear backlog fast</span>
          </div>

          {/* Risk Aversion */}
          <div className="space-y-1.5 p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/80 dark:border-slate-700/80">
            <div className="flex justify-between text-xs font-bold">
              <span className="text-slate-700 dark:text-slate-300">Risk Aversion</span>
              <span className="font-mono text-emerald-600 font-black">{weights.riskAversion}%</span>
            </div>
            <input
              type="range"
              min="0"
              max="100"
              value={weights.riskAversion}
              onChange={e => setWeights({ ...weights, riskAversion: Number(e.target.value) })}
              className="w-full accent-emerald-600 cursor-pointer"
            />
            <span className="text-[10px] text-slate-400 font-medium block">Zero machine breakdown</span>
          </div>

          {/* Simplicity */}
          <div className="space-y-1.5 p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/80 dark:border-slate-700/80">
            <div className="flex justify-between text-xs font-bold">
              <span className="text-slate-700 dark:text-slate-300">Simplicity</span>
              <span className="font-mono text-amber-600 font-black">{weights.simplicity}%</span>
            </div>
            <input
              type="range"
              min="0"
              max="100"
              value={weights.simplicity}
              onChange={e => setWeights({ ...weights, simplicity: Number(e.target.value) })}
              className="w-full accent-amber-600 cursor-pointer"
            />
            <span className="text-[10px] text-slate-400 font-medium block">Easy for shift crew</span>
          </div>
        </div>
      </div>

      {/* 6. SIDE-BY-SIDE NOISE-FREE COMPARISON MATRIX */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 sm:p-6 shadow-xs space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Scale className="h-4 w-4 text-primary dark:text-blue-400" />
            <h3 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider">
              Side-by-Side Operational Comparison (Signal vs Noise)
            </h3>
          </div>
          <span className="text-xs text-slate-500 font-semibold">
            {scoredOptions.length} Options Evaluated
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {scoredOptions.map(({ option, compositeScore, rank }) => {
            const isWinner = rank === 1;

            return (
              <div
                key={option.id}
                className={`p-5 rounded-3xl border transition-all space-y-4 text-left ${
                  isWinner
                    ? 'bg-emerald-50/40 dark:bg-emerald-950/20 border-emerald-500/80 shadow-md ring-2 ring-emerald-500/20'
                    : 'bg-slate-50/50 dark:bg-slate-800/40 border-slate-200 dark:border-slate-800'
                }`}
              >
                {/* Header */}
                <div className="flex items-start justify-between gap-3 border-b border-slate-200/80 dark:border-slate-700/80 pb-3">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className={`px-2 py-0.5 rounded-md text-[10px] font-black uppercase ${
                        isWinner
                          ? 'bg-emerald-500 text-white'
                          : 'bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-300'
                      }`}>
                        {isWinner ? '★ WINNER (Rank #1)' : `Rank #${rank}`}
                      </span>
                      {option.estimatedCostPerUnit && (
                        <span className="font-mono text-xs font-extrabold text-slate-600 dark:text-slate-300">
                          {option.estimatedCostPerUnit}
                        </span>
                      )}
                    </div>
                    <h4 className="text-base font-black text-slate-900 dark:text-white mt-1">
                      {option.name}
                    </h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">
                      {option.tagline}
                    </p>
                  </div>

                  <div className="text-right shrink-0">
                    <span className="text-[10px] font-bold text-slate-400 uppercase block">Score</span>
                    <span className="text-lg font-black font-mono text-slate-900 dark:text-white">
                      {compositeScore}/100
                    </span>
                  </div>
                </div>

                {/* Operational Reality (Cut the fluff) */}
                <div className="bg-white dark:bg-slate-900 p-3 rounded-2xl border border-slate-200/80 dark:border-slate-800 space-y-1">
                  <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block flex items-center gap-1">
                    <Zap className="h-3 w-3 text-amber-500" /> Operational Reality (The Truth)
                  </span>
                  <p className="text-xs font-semibold text-slate-700 dark:text-slate-300 leading-relaxed">
                    {option.operationalReality}
                  </p>
                </div>

                {/* Pros & Cons */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                  <div className="space-y-1 bg-white dark:bg-slate-900 p-2.5 rounded-xl border border-slate-100 dark:border-slate-800">
                    <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 uppercase">Key Pros</span>
                    <ul className="space-y-1">
                      {option.keyPros.map((pro, i) => (
                        <li key={i} className="text-slate-700 dark:text-slate-300 font-medium flex items-start gap-1">
                          <span className="text-emerald-500 font-black">✓</span>
                          <span>{pro}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="space-y-1 bg-white dark:bg-slate-900 p-2.5 rounded-xl border border-slate-100 dark:border-slate-800">
                    <span className="text-[10px] font-bold text-red-600 dark:text-red-400 uppercase">Key Cons</span>
                    <ul className="space-y-1">
                      {option.keyCons.map((con, i) => (
                        <li key={i} className="text-slate-700 dark:text-slate-300 font-medium flex items-start gap-1">
                          <span className="text-red-500 font-black">✗</span>
                          <span>{con}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Dealbreakers */}
                {option.dealbreakers.length > 0 && option.dealbreakers[0] !== 'None' && (
                  <div className="p-2.5 bg-red-50 dark:bg-red-950/40 rounded-xl border border-red-200 dark:border-red-800/60 text-xs font-bold text-red-700 dark:text-red-300 flex items-start gap-2">
                    <AlertTriangle className="h-4 w-4 shrink-0 text-red-500 mt-0.5" />
                    <div>
                      <span className="uppercase text-[9px] font-black block">Dealbreaker Condition:</span>
                      <span>{option.dealbreakers.join(', ')}</span>
                    </div>
                  </div>
                )}

                {/* Best Suited For */}
                <div className="text-[11px] text-slate-500 dark:text-slate-400 pt-1">
                  <strong>Best Suited For:</strong> {option.bestSuitedFor}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* 7. HONEST UNCERTAINTIES & UNKNOWNS AUDITOR (NO GUESSING!) */}
      <div className="bg-amber-50/80 dark:bg-amber-950/30 border border-amber-300 dark:border-amber-800/80 rounded-3xl p-5 sm:p-6 space-y-4">
        <div className="flex items-center gap-2.5 text-amber-800 dark:text-amber-300">
          <div className="p-2 rounded-xl bg-amber-100 dark:bg-amber-900/60 text-amber-700 dark:text-amber-300">
            <AlertTriangle className="h-5 w-5" />
          </div>
          <div>
            <h3 className="font-extrabold text-sm uppercase tracking-wider">
              Critical Uncertainty & Risk Audit (No AI Guessing)
            </h3>
            <p className="text-[11px] font-medium text-amber-700 dark:text-amber-400">
              The AI highlights missing factory variables instead of guessing. Verify these parameters on the floor before final execution.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
          {criticalUncertainties.map((item) => (
            <div
              key={item.id}
              className="bg-white dark:bg-slate-900 p-4 rounded-2xl border border-amber-200/80 dark:border-amber-800/60 space-y-2 text-xs text-left"
            >
              <div className="flex justify-between items-center border-b border-slate-100 dark:border-slate-800 pb-2">
                <span className="font-black text-slate-900 dark:text-white">
                  {item.variable}
                </span>
                <span className="px-2 py-0.5 rounded-full text-[9px] font-black uppercase bg-red-100 dark:bg-red-950/60 text-red-700 dark:text-red-300 border border-red-200">
                  {item.impactOnDecision} Impact
                </span>
              </div>
              <p className="text-slate-600 dark:text-slate-400 font-medium">
                {item.whyUncertain}
              </p>
              <div className="p-2 rounded-xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200/60 dark:border-amber-800/60 text-[11px] font-bold text-amber-800 dark:text-amber-300 flex items-center gap-1.5">
                <CheckCircle2 className="h-3.5 w-3.5 shrink-0 text-amber-600" />
                <span>Verify: {item.actionToVerify}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
};

export default AiDecisionAgentView;
